name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
          id: time
          with:
            timeZone: $TIMEZONE
            format: 'YYYY-MM-DD'
      - run:
        - rm -f $DIR/*
        - touch $DIR/$TIME
        - cd $WORKSPACE
        - git add -A
        - git commit -am "$TIME"
        - git push
      - env:
          TIMEZONE: 9 # UTC
          TIME: ${{ steps.time.outputs.time }}
          WORKSPACE: ${{ github.workspace }}
          DIR: $WORKSPACE/automatic
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
