name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9 # UTC
          format: 'YYYY-MM-DD'
      - name: Run daily commit machine
        run: |
          git --version
          git clone $GIT_REMOTE
          echo "git clone complete."
          
          cd $REPOSITORY
          echo "found cloned repository."
          
          git config user.name daily-commit-machine
          git config user.email molruexception.com
          echo "git config setup complete."
          
          rm -f automatic
          mkdir automatic
          touch automatic/${TIME}.json
          echo "update daily commit file."
          
          git add -A
          git commit -am "$TIME"
          git push origin master
          echo "push daily commit file."
          echo "job complete."
          
        env:
          TIME: ${{ steps.time.outputs.time }}
          USERNAME: MolruException
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_REMOTE: https://${USERNAME}:${GH_TOKEN}@github.com/${{ github.repository }}.git
          REPOSITORY: daily-commit-machine
