name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run daily commit machine
        run: |
          sudo timedatectl set-timezone $TIMEZONE
          echo "Set timezone to ${TIMEZONE}"
          
          date +%s > daily-commit-machine.csv
          echo "update daily commit file."
          
          git --version
          git config --global user.name 'daily-commit-machine'
          git config --global user.email 'molruexception.com'
          git commit -am "Auto committed at $(date +'%Y-%m-%d')"
          git push
          
          echo "push daily commit file."
          echo "job complete."
          
        env:
          TIMEZONE: Asia/Seoul
          # GH_USERNAME: MolruException
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # GIT_REMOTE: https://${GH_USERNAME}:${GH_TOKEN}@github.com/${{ github.repository }}.git
          # REPOSITORY: daily-commit-machine
