name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run daily commit machine
        run: |
          sudo timedatectl set-timezone $TIMEZONE
          echo "Set timezone to ${TIMEZONE}"
          echo "Set time to $(date +'%Y-%m-%d')"
          
          git --version
          git clone $GIT_REMOTE
          echo "git clone complete."
          
          cd $REPOSITORY
          echo "found cloned repository."
          
          git config user.name daily-commit-machine
          git config user.email molruexception.com
          echo "git config setup complete."
          
          rm -f automatic
          mkdir automatic/AUTO-$(date +'%Y-%m-%d').json
          echo "update daily commit file."
          
          git add -A
          git commit -am "Auto committed at $(date +'%Y-%m-%d')"
          git push
          
          echo "push daily commit file."
          echo "job complete."
          
        env:
          TIMEZONE: Asia/Seoul
          GH_USERNAME: MolruException
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_REMOTE: https://${GH_USERNAME}:${GH_TOKEN}@github.com/${{ github.repository }}.git
          REPOSITORY: daily-commit-machine
