name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"

env:
  TIMEZONE: 9 # UTC
  TIME: ${{ steps.time.outputs.time }}
  WORKSPACE: ${{ github.workspace }}
  DIR: $WORKSPACE/automatic
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Setup
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: $TIMEZONE
        format: 'YYYY-MM-DD'

    - name: Update file
      run:
        - rm -f $DIR/*
        - touch $DIR/$TIME

    - name: Commit & Push file
      run:
        - cd $WORKSPACE
        - git add -A
        - git commit -am "$TIME"
        - git push
