name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9 # UTC
          format: 'YYYY-MM-DD'
      - name: Run daily commit machine
        run: |
          git --version
          git clone ${REPOSITORY}.git
          git config user.name $GIT_USER
          echo "git config user.name $GIT_USER"
          git config user.email $GIT_EMAIL
          echo "git config user.email $GIT_EMAIL"
          rm -f $DIR/*
          mkdir -p $DIR/${TIME}.json
          git add -A
          git commit -am "$TIME"
          git push
        env:
          GIT_USER: daily-commit-machine
          GIT_EMAIL: molruexception@gmail.com
          REPOSITORY: https://github.com/${{ github.repository }}
          DIR: /automatic
          TIME: ${{ steps.time.outputs.time }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
