name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9 # UTC
          format: 'YYYY-MM-DD'
      - run:
        - git clone $REPOSITORY.git
        - rm -f $DIR/*
        - touch $DIR/$TIME
        - cd $WORKSPACE
        - git add -A
        - git commit -am "$TIME"
        - git push
        env:
          REPOSITORY: github.com/${{ github.repository }}
          DIR: $REPOSITORY/automatic
          TIME: ${{ steps.time.outputs.time }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
