name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9 # UTC
          format: 'YYYY-MM-DD'
      - name: Run daily commit machine
        run: |
          IN = "${{ github.repository }}"
          arrIN = (${IN//// })
          echo "DIR=${arrIN[1]}" >> $GITHUB_ENV
          git --version
          git clone $REPOSITORY
          cd $DIR
          git config user.name daily-commit-machine
          git config user.email molruexception.com
          rm -f $DIR/daily-commit-machine/*
          mkdir -p $DIR/daily-commit-machine/${TIME}.json
          git add -A
          git commit -am "$TIME"
          git push
        env:
          TIME: ${{ steps.time.outputs.time }}
          USERNAME: MolruException
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: https://${USERNAME}:${GH_TOKEN}@github.com/${{ github.repository }}.git
