name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 9 # UTC
          format: 'YYYY-MM-DD'
      - name: Run daily commit machine
        run: |
          sudo apt-get install git
          sudo apt install git
          git --version
          git config user.name $GIT_USER
          git config user.email $GIT_EMAIL
          git clone $REPOSITORY.git
          rm -f $DIR/*
          touch $DIR/$TIME
          cd $WORKSPACE
          git add -A
          git commit -am "$TIME"
          git push
        env:
          GIT_USER: daily-commit-machine
          GIT_EMAIL: molruexception@gmail.com
          REPOSITORY: github.com/${{ github.repository }}
          DIR: $REPOSITORY/automatic
          TIME: ${{ steps.time.outputs.time }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
