name: Run daily commit machine

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run daily commit machine
        run: |
          sudo timedatectl set-timezone "${TIMEZONE}" 
          echo "Set timezone to ${TIMEZONE}."
          echo "TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          
          git --version
          git clone $GIT_REMOTE
          echo "git clone complete."
          
          cd $REPOSITORY
          echo "found cloned repository."
          
          git config user.name daily-commit-machine
          git config user.email molruexception.com
          echo "git config setup complete."
          
          rm -f automatic
          mkdir automatic
          touch automatic/AUTO-${{ env.GITHUB_SHA_SHORT }}.json
          echo "update daily commit file."
          
          git add -A
          git commit -am "Auto committed at ${{ env.GITHUB_SHA_SHORT }}"
          git remote set-url origin $GIT_REMOTE
          
          echo "push daily commit file."
          echo "job complete."
          
        env:
          TIMEZONE: Asia/Seoul
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_REMOTE: https://${GH_TOKEN}@github.com/${{ github.repository }}.git
          REPOSITORY: daily-commit-machine
